### ISSUE TITLE
img link not being added into currentUser()

### ISSUE THREAD

**Issue by gamalielhere** [gamalielhere/park_here#2]
1.) AAU, I would like to add a profile image to personalize my own profile.
2.) No visible errors.
3.) added img to user model, added img key to data key in user controller, tried to render it back to the update form the way it was with the name and email, didn't work.

**Comment by h4w5** [comment]
Can you:

- explain what it should do if it "works,"
- link to the components you are describing above,
- attach images of your console logging each of these steps, etc.

**Comment by EARnagram** [comment]
Is this closed?

**Comment by gamalielhere** [comment]
@EARnagram not yet.
